// Package config loads and validates a project's syl configuration.
package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
)

const configRelativePath = ".syl/config.toml"

const (
	TrackerGitHub Tracker = "github"
	TrackerLocal  Tracker = "local"
)

const (
	HarnessClaude   Harness = "claude"
	HarnessCodex    Harness = "codex"
	HarnessOpenCode Harness = "opencode"
)

const (
	EffortLow    Effort = "low"
	EffortMedium Effort = "medium"
	EffortHigh   Effort = "high"
	EffortXHigh  Effort = "xhigh"
)

const (
	defaultPlanMCP      = true
	defaultImplementMCP = true
	defaultReviewMCP    = false
)

// DefaultWorktreeRoot is the user-level directory where syl creates
// implementation worktrees when a project does not configure another root.
const DefaultWorktreeRoot = "~/.syl/worktrees"

var ErrNotFound = errors.New("syl config not found")

type Tracker string
type Harness string
type Effort string

// WriteMode controls whether Write creates a new config or replaces an
// existing one.
type WriteMode bool

const (
	NoOverwrite       WriteMode = false
	OverwriteExisting WriteMode = true
)

type Config struct {
	Tracker       TrackerConfig
	Roles         RolesConfig
	Loop          LoopConfig
	Notifications NotificationsConfig
	Worktree      WorktreeConfig
}

type TrackerConfig struct {
	Issues  Tracker
	Reviews Tracker
}

type RolesConfig struct {
	Plan      RoleConfig
	Implement RoleConfig
	Review    RoleConfig
}

type RoleConfig struct {
	Harness Harness
	Model   string
	Effort  Effort
	MCP     bool
}

type LoopConfig struct {
	MaxIterations int
}

type NotificationsConfig struct {
	Enabled bool
}

type WorktreeConfig struct {
	Root  string
	Setup string
}

type rawConfig struct {
	Tracker       rawTracker       `toml:"tracker"`
	Roles         rawRoles         `toml:"roles"`
	Loop          rawLoop          `toml:"loop"`
	Notifications rawNotifications `toml:"notifications"`
	Worktree      rawWorktree      `toml:"worktree"`
}

type rawTracker struct {
	Issues  string `toml:"issues"`
	Reviews string `toml:"reviews"`
}

type rawRoles struct {
	Plan      rawRole `toml:"plan"`
	Implement rawRole `toml:"implement"`
	Review    rawRole `toml:"review"`
}

type rawRole struct {
	Harness string `toml:"harness"`
	Model   string `toml:"model"`
	Effort  string `toml:"effort"`
	MCP     any    `toml:"mcp"`
}

type rawLoop struct {
	MaxIterations int `toml:"max_iterations"`
}

type rawNotifications struct {
	Enabled bool `toml:"enabled"`
}

type rawWorktree struct {
	Root  string `toml:"root"`
	Setup string `toml:"setup"`
}

func Path(projectRoot string) string {
	return filepath.Join(projectRoot, configRelativePath)
}

func Load(projectRoot string) (Config, error) {
	path := Path(projectRoot)
	contents, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return Config{}, fmt.Errorf("%w: %s; run syl init", ErrNotFound, path)
		}
		return Config{}, fmt.Errorf("read config %s: %w", path, err)
	}

	var raw rawConfig
	metadata, err := toml.Decode(string(contents), &raw)
	if err != nil {
		return Config{}, fmt.Errorf("malformed TOML in %s: %w", path, err)
	}
	if keys := metadata.Undecoded(); len(keys) > 0 {
		unknown := make([]string, 0, len(keys))
		for _, key := range keys {
			unknown = append(unknown, key.String())
		}
		sort.Strings(unknown)
		return Config{}, fmt.Errorf("unknown config key %q", unknown[0])
	}

	return validate(raw, metadata)
}

func Init(projectRoot string) (string, error) {
	return Write(projectRoot, defaultConfigValue(), NoOverwrite)
}

// Write writes the project configuration using the exact schema consumed by
// Load. NoOverwrite leaves an existing config untouched.
func Write(projectRoot string, cfg Config, mode WriteMode) (string, error) {
	path := Path(projectRoot)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", fmt.Errorf("create .syl directory: %w", err)
	}

	flags := os.O_WRONLY | os.O_CREATE
	if mode == OverwriteExisting {
		flags |= os.O_TRUNC
	} else {
		flags |= os.O_EXCL
	}
	file, err := os.OpenFile(path, flags, 0o644)
	if err != nil {
		if errors.Is(err, os.ErrExist) && mode == NoOverwrite {
			return "", fmt.Errorf("config already exists at %s", path)
		}
		return "", fmt.Errorf("create config %s: %w", path, err)
	}
	defer file.Close()
	if _, err := file.WriteString(Render(cfg)); err != nil {
		return "", fmt.Errorf("write config %s: %w", path, err)
	}
	return path, nil
}

// Render formats a validated configuration as a committable TOML file.
func Render(cfg Config) string {
	return fmt.Sprintf(`# Generated by syl init.
[tracker]
issues = %q
reviews = %q

[roles.plan]
harness = %q
model = %q
effort = %q
# mcp = true inherits user/project MCP configuration; false strips it for Claude.
# Codex ignores this field. Omitted defaults are true for plan and implement, and false for review.
mcp = %t

[roles.implement]
harness = %q
model = %q
effort = %q
# mcp = true inherits user/project MCP configuration; false strips it for Claude.
# Codex ignores this field. Omitted defaults are true for plan and implement, and false for review.
mcp = %t

[roles.review]
harness = %q
model = %q
effort = %q
# mcp = true inherits user/project MCP configuration; false strips it for Claude.
# Codex ignores this field. Omitted defaults are true for plan and implement, and false for review.
# Hooks that require MCP may cause one blocked-then-retried tool call in lean sessions.
mcp = %t

[loop]
max_iterations = %d

[notifications]
enabled = %t

[worktree]
root = %q
# A shell command used to provision dependencies in a fresh worktree.
# Example: setup = "npm ci"
setup = %q
`, cfg.Tracker.Issues, cfg.Tracker.Reviews,
		cfg.Roles.Plan.Harness, cfg.Roles.Plan.Model, cfg.Roles.Plan.Effort,
		cfg.Roles.Plan.MCP,
		cfg.Roles.Implement.Harness, cfg.Roles.Implement.Model, cfg.Roles.Implement.Effort,
		cfg.Roles.Implement.MCP,
		cfg.Roles.Review.Harness, cfg.Roles.Review.Model, cfg.Roles.Review.Effort,
		cfg.Roles.Review.MCP,
		cfg.Loop.MaxIterations, cfg.Notifications.Enabled,
		worktreeRoot(cfg.Worktree.Root), cfg.Worktree.Setup)
}

func worktreeRoot(root string) string {
	if strings.TrimSpace(root) == "" {
		return DefaultWorktreeRoot
	}
	return root
}

func defaultConfigValue() Config {
	return Config{
		Tracker: TrackerConfig{Issues: TrackerGitHub, Reviews: TrackerLocal},
		Roles: RolesConfig{
			Plan:      RoleConfig{Harness: HarnessClaude, Model: "claude-opus-5", Effort: EffortHigh, MCP: true},
			Implement: RoleConfig{Harness: HarnessCodex, Model: "gpt-5.6-luna", Effort: EffortXHigh, MCP: true},
			Review:    RoleConfig{Harness: HarnessClaude, Model: "claude-sonnet-5", Effort: EffortMedium},
		},
		Loop:          LoopConfig{MaxIterations: 3},
		Notifications: NotificationsConfig{Enabled: true},
		Worktree:      WorktreeConfig{Root: DefaultWorktreeRoot},
	}
}

func validate(raw rawConfig, metadata toml.MetaData) (Config, error) {
	issues, err := parseTracker("tracker.issues", raw.Tracker.Issues)
	if err != nil {
		return Config{}, err
	}
	reviews, err := parseTracker("tracker.reviews", raw.Tracker.Reviews)
	if err != nil {
		return Config{}, err
	}
	if issues == TrackerLocal && reviews == TrackerGitHub {
		return Config{}, errors.New(`tracker.reviews = "github" requires tracker.issues = "github" so review comments have a remote issue`)
	}
	plan, err := parseRole("roles.plan", raw.Roles.Plan, defaultPlanMCP)
	if err != nil {
		return Config{}, err
	}
	implement, err := parseRole("roles.implement", raw.Roles.Implement, defaultImplementMCP)
	if err != nil {
		return Config{}, err
	}
	review, err := parseRole("roles.review", raw.Roles.Review, defaultReviewMCP)
	if err != nil {
		return Config{}, err
	}

	maxIterations := 3
	if metadata.IsDefined("loop", "max_iterations") {
		maxIterations = raw.Loop.MaxIterations
	}
	if maxIterations < 1 {
		return Config{}, fmt.Errorf("loop.max_iterations must be positive; got %d", maxIterations)
	}

	notificationsEnabled := true
	if metadata.IsDefined("notifications", "enabled") {
		notificationsEnabled = raw.Notifications.Enabled
	}

	worktreeRoot := DefaultWorktreeRoot
	if metadata.IsDefined("worktree", "root") {
		worktreeRoot = strings.TrimSpace(raw.Worktree.Root)
		if worktreeRoot == "" {
			return Config{}, errors.New("worktree.root: is required")
		}
	}

	return Config{
		Tracker: TrackerConfig{Issues: issues, Reviews: reviews},
		Roles: RolesConfig{
			Plan: plan, Implement: implement, Review: review,
		},
		Loop:          LoopConfig{MaxIterations: maxIterations},
		Notifications: NotificationsConfig{Enabled: notificationsEnabled},
		Worktree:      WorktreeConfig{Root: worktreeRoot, Setup: raw.Worktree.Setup},
	}, nil
}

func parseTracker(key, value string) (Tracker, error) {
	return parseEnum(key, value, []Tracker{TrackerGitHub, TrackerLocal}, "github or local")
}

func parseRole(prefix string, raw rawRole, defaultMCP bool) (RoleConfig, error) {
	harness, err := parseEnum(prefix+".harness", raw.Harness,
		[]Harness{HarnessClaude, HarnessCodex, HarnessOpenCode}, "claude, codex, or opencode")
	if err != nil {
		return RoleConfig{}, err
	}
	if strings.TrimSpace(raw.Model) == "" {
		return RoleConfig{}, fmt.Errorf("%s.model: is required", prefix)
	}
	if harness == HarnessClaude && !strings.HasPrefix(raw.Model, "claude-") {
		return RoleConfig{}, fmt.Errorf(`%s.model: invalid value %q; want a model starting with "claude-"`, prefix, raw.Model)
	}

	effort, err := parseEnum(prefix+".effort", raw.Effort,
		[]Effort{EffortLow, EffortMedium, EffortHigh, EffortXHigh}, "low, medium, high, or xhigh")
	if err != nil {
		return RoleConfig{}, err
	}

	mcp, err := parseOptionalBool(prefix+".mcp", raw.MCP, defaultMCP)
	if err != nil {
		return RoleConfig{}, err
	}

	return RoleConfig{Harness: harness, Model: raw.Model, Effort: effort, MCP: mcp}, nil
}

func parseOptionalBool(key string, value any, defaultValue bool) (bool, error) {
	if value == nil {
		return defaultValue, nil
	}
	enabled, ok := value.(bool)
	if !ok {
		return false, fmt.Errorf("%s: invalid value %q; want true or false", key, fmt.Sprint(value))
	}
	return enabled, nil
}

func parseEnum[T ~string](key, value string, valid []T, want string) (T, error) {
	var zero T
	if strings.TrimSpace(value) == "" {
		return zero, fmt.Errorf("%s: is required", key)
	}
	for _, candidate := range valid {
		if T(value) == candidate {
			return candidate, nil
		}
	}
	return zero, fmt.Errorf("%s: invalid value %q; want %s", key, value, want)
}
